// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FriendCodeController from "./friend_code_controller"
application.register("friend-code", FriendCodeController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import LocaleController from "./locale_controller"
application.register("locale", LocaleController)

import ScheduleTableController from "./schedule_table_controller"
application.register("schedule-table", ScheduleTableController)

import SessionsController from "./sessions_controller"
application.register("sessions", SessionsController)

import WordCounterController from "./word_counter_controller"
application.register("word-counter", WordCounterController)
