inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - ./db/**/*
    - ./bin/**/*
    - ./vendor/**/*
    - ./config/**/*

Metrics/BlockLength:
  Exclude:
    - ./test/**/*

Metrics/ClassLength:
  Exclude:
    - ./test/**/*
