# Name of the container image.
image: <%= ENV['MIE_GOOGLE_CLOUD_PROJECT'] %>/mie-staging/mie

# Deploy to these servers.
servers:
  - mie-staging-vm.asia-northeast1-b.<%= ENV['MIE_GOOGLE_CLOUD_PROJECT'] %>

# Credentials for your image host.
registry:
  server: asia-northeast1-docker.pkg.dev/<%= ENV['MIE_GOOGLE_CLOUD_PROJECT'] %>/mie-staging

# Configure builder setup.
builder:
  arch: amd64
