name: Rubocop - Run linter

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
